<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<script>
    setTimeout(function() {
        jQuery(document).ready(function() {
            $.fn.datepicker.dates['pt_BR'] = {
                days: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
                daysShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
//                daysMin: ["Do", "Se", "Te", "Qa", "Qi", "Sx", "Sa"],
                daysMin: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
                months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
                monthsShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
                today: "Hoje",
                clear: "Limpar",
                format: "dd/mm/yyyy",
                titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
                weekStart: 0
            };

            jQuery('#dt_nascimento_cliente').datepicker({
                format: 'dd/mm/yyyy',
                language: 'pt_BR',
                autoclose: true,
                todayHighlight: true
            });

            jQuery('#cpf_cliente').mask('000.000.000-00');
            jQuery('#telefone_cliente').mask('(00) 0000-00000');
            jQuery('#dt_nascimento_cliente').mask('00/00/0000');
            jQuery('#celular_cliente').mask('(00) 0000-00000');
            jQuery('#cep_cliente').mask('00.000-000');

            jQuery('#uf_cliente').change(function () {
                jQuery('#cidade_cliente').html('<option value="">Carregando...</option>');
                jQuery.ajax({
                    url: '/ajax/cidades/' + jQuery(this).val(),
                    type: 'GET',
                    dataType: 'JSON',
                    success: function( json ) {
                        jQuery('#cidade_cliente').html('<option value="">Selecionar cidade</option>');
                        jQuery.each(json, function(i, value) {
                            jQuery('#cidade_cliente').append(jQuery('<option>').text(value.nomeCidade).attr('value', value.idCidade));
                        });
                    }
                });
            });
        });
    }, 100);
</script>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Clientes
                <small>Cadastrar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Clientes</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Horizontal Form Example -->
    <div class="col-lg-12">
        <?php
        if ($this->mensagem != null)
        {
            echo '<div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>Atenção!</strong> ' . $this->mensagem . '</div>';
        }
        ?>
        <a href="/clientes" class="btn btn-default btn-square">Listar Clientes</a>
        <br />
        <br />
        <div class="portlet portlet-green">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Cadastro de Cliente</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#horizontalFormExample"><i class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="horizontalFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <form class="form-horizontal" role="form" method="POST" name="upload-form" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Nome</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="nome_cliente" name="nome_cliente" placeholder="Nome" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">CPF</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="cpf_cliente" name="cpf_cliente" placeholder="CPF" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">RG</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="rg_cliente" name="rg_cliente" placeholder="RG" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Telefone</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="telefone_cliente" name="telefone_cliente" placeholder="Telefone" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Celular</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="celular_cliente" name="celular_cliente" placeholder="Celular" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Data de Nascimento</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="dt_nascimento_cliente" name="dt_nascimento_cliente" placeholder="Data de Nascimento" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">E-mail</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="email_cliente" name="email_cliente" placeholder="E-mail" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Sexo</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><input name="sexo_cliente" value="Masculino" type="radio"> Masculino</label>
                                <label class="radio-inline"><input name="sexo_cliente" value="Feminino" type="radio"> Feminino</label>
                                <label class="radio-inline"><input name="sexo_cliente" value="Outro" type="radio"> Outro</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">CEP</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="cep_cliente" name="cep_cliente" placeholder="CEP" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Endereço</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="endereco_cliente" name="endereco_cliente" placeholder="Endereço" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Número</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="numero_cliente" name="numero_cliente" placeholder="Número" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Complemento</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="complemento_cliente" name="complemento_cliente" placeholder="Complemento" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">UF</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="uf_cliente" id="uf_cliente">
                                    <option value="">Selecione</option>
                                    <?php foreach ($this->estados as $estado) { ?>
                                    <option value="<?php echo $estado->getIdEstado(); ?>"><?php echo $estado->getUfEstado(); ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Cidade</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="cidade_cliente" id="cidade_cliente">
                                    <option value="">Selecione Estado</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Foto</label>
                            <div class="col-sm-10">
                                <input type="file" id="foto_cliente" name="foto_cliente">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default btn-square">Cadastrar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Horizontal Form Example -->
</div>