<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Clientes
                <small>Lista</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Clientes</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Inline Form Example -->
    <!-- .col-lg-12 (open) -->
    <div class="col-lg-12">
        <a href="/clientes/cadastro" class="btn btn-green btn-square">Cadastrar Cliente</a>
        <br />
        <br />
        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Clientes</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#inlineFormExample"><i class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="inlineFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                <div class="table-responsive">
                <table id="example-table" class="table table-striped table-bordered table-hover table-green">
                <thead>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>CPF</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->clientes as $cliente) { ?>
                <tr>
                    <td><?php echo $cliente->getIdCliente(); ?></td>
                    <td><?php echo $cliente->getNomeCliente(); ?></td>
                    <td><?php echo $cliente->getCpfCliente(); ?></td>
                    <td width="20%">
                        <a href="/clientes/visualiza/<?php echo $cliente->getIdCliente(); ?>" class="btn btn-purple btn-square"><i class="fa fa-search"></i> Visualizar</a>
                        <a href="/clientes/edita/<?php echo $cliente->getIdCliente(); ?>" class="btn btn-blue btn-square"><i class="fa fa-edit"></i> Editar</a>
                        <a href="#delete" data-toggle="tooltip" data-placement="top" title="Apagar" class="delete_open btn btn-red btn-square" onclick="deletaCliente(<?php echo $cliente->getIdCliente(); ?>, '<?php echo $cliente->getNomeCliente(); ?>');"><i class="fa fa-trash-o"></i> Deletar</a>
                    </td>
                </tr>
                <?php } ?>
                </tbody>
                </table>
                </div>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Inline Form Example -->
</div>

<!-- Delete Notification Box -->
<div id="delete">
    <div class="logout-message">
        <br />
        <h3>
            <i class="fa fa-sign-out text-green"></i> Deseja Apagar <b id="nome_cliente_apagar">--</b>?
        </h3>
        <p>Clique em "Sim" para apagar este usuário.</p>
        <ul class="list-inline">
            <li>
                <a href="#" class="btn btn-green" id="url_cliente_apagar">
                    <strong>Sim</strong>
                </a>
            </li>
            <li>
                <button class="delete_close btn btn-green">Cancelar</button>
            </li>
        </ul>
    </div>
</div>
<!-- /#delete -->

<script>
    function deletaCliente(id, nome)
    {
        $('#nome_cliente_apagar').html(nome);
        $('#url_cliente_apagar').attr('href', '/clientes/deleta/' + id);
    }
</script>