<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Funcionários
                <small>Cadastro</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Funcionários</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Horizontal Form Example -->
    <div class="col-lg-12">
        <a href="/funcionarios" class="btn btn-default btn-square">Listar Funcionários</a>
        <br />
        <br />
        <div class="portlet portlet-green">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Visualizar Funcionário</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#horizontalFormExample"><i class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="horizontalFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <form class="form-horizontal" role="form" method="POST" name="upload-form" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Nome</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getNomeFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">CPF</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getCpfFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">RG</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getRgFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Telefone</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getTelefoneFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Celular</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getCelularFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Data de Nascimento</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo date('d/m/Y', $this->funcionario->getDtNascimentoFuncionario()); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">E-mail</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getEmailFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Sexo</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getSexoFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">CEP</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getCepFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Endereço</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getEnderecoFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Número</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getNumeroFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Complemento</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getComplementoFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">UF</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->estado->getUfEstado(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Cidade</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->cidade->getNomeCidade(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Função</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->funcionario->getFuncaoFuncionario(); ?></label>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Horizontal Form Example -->
</div>