<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fornecedor extends \Application\Entity\Fornecedor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'idFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'dtCadastroFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'nomeFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'razaoSocialFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'cnpjFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'telefoneFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'celularFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'cepFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'enderecoFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'numeroFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'complementoFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'cidadeFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'ufFornecedor');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'idFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'dtCadastroFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'nomeFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'razaoSocialFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'cnpjFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'telefoneFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'celularFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'cepFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'enderecoFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'numeroFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'complementoFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'cidadeFornecedor', '' . "\0" . 'Application\\Entity\\Fornecedor' . "\0" . 'ufFornecedor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fornecedor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdFornecedor()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdFornecedor();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFornecedor', array());

        return parent::getIdFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCadastroFornecedor($dtCadastroFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCadastroFornecedor', array($dtCadastroFornecedor));

        return parent::setDtCadastroFornecedor($dtCadastroFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCadastroFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCadastroFornecedor', array());

        return parent::getDtCadastroFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeFornecedor($nomeFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeFornecedor', array($nomeFornecedor));

        return parent::setNomeFornecedor($nomeFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeFornecedor', array());

        return parent::getNomeFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazaoSocialFornecedor($razaoSocialFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazaoSocialFornecedor', array($razaoSocialFornecedor));

        return parent::setRazaoSocialFornecedor($razaoSocialFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazaoSocialFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazaoSocialFornecedor', array());

        return parent::getRazaoSocialFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnpjFornecedor($cnpjFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnpjFornecedor', array($cnpjFornecedor));

        return parent::setCnpjFornecedor($cnpjFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpjFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpjFornecedor', array());

        return parent::getCnpjFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneFornecedor($telefoneFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneFornecedor', array($telefoneFornecedor));

        return parent::setTelefoneFornecedor($telefoneFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneFornecedor', array());

        return parent::getTelefoneFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCelularFornecedor($celularFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCelularFornecedor', array($celularFornecedor));

        return parent::setCelularFornecedor($celularFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCelularFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelularFornecedor', array());

        return parent::getCelularFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCepFornecedor($cepFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCepFornecedor', array($cepFornecedor));

        return parent::setCepFornecedor($cepFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCepFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCepFornecedor', array());

        return parent::getCepFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnderecoFornecedor($enderecoFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnderecoFornecedor', array($enderecoFornecedor));

        return parent::setEnderecoFornecedor($enderecoFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnderecoFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnderecoFornecedor', array());

        return parent::getEnderecoFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroFornecedor($numeroFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroFornecedor', array($numeroFornecedor));

        return parent::setNumeroFornecedor($numeroFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroFornecedor', array());

        return parent::getNumeroFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplementoFornecedor($complementoFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplementoFornecedor', array($complementoFornecedor));

        return parent::setComplementoFornecedor($complementoFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplementoFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplementoFornecedor', array());

        return parent::getComplementoFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidadeFornecedor($cidadeFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidadeFornecedor', array($cidadeFornecedor));

        return parent::setCidadeFornecedor($cidadeFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidadeFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidadeFornecedor', array());

        return parent::getCidadeFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setUfFornecedor($ufFornecedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUfFornecedor', array($ufFornecedor));

        return parent::setUfFornecedor($ufFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getUfFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUfFornecedor', array());

        return parent::getUfFornecedor();
    }

}
