<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Pedidos
                <small>Listar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Pedidos</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Inline Form Example -->
    <!-- .col-lg-12 (open) -->
    <div class="col-lg-12">
        <a href="/pedidos/cadastro" class="btn btn-green btn-square">Cadastrar Pedido</a>
        <br />
        <br />
        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Pedidos</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#inlineFormExample"><i class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="inlineFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                <div class="table-responsive">
                <table id="example-table" class="table table-striped table-bordered table-hover table-green">
                <thead>
                <tr>
                    <th>Código</th>
                    <th>Observações</th>
                    <th>Valor</th>
                    <th>Status</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->pedidos as $pedido) { ?>
                <tr>
                    <td><?php echo $pedido->getIdPedido(); ?></td>
                    <td><?php echo $pedido->getObsPedido(); ?></td>
                    <td>R$ <?php echo $pedido->getValorPedido(); ?></td>
                    <td><?php
                        switch ($pedido->getStatusPedido()) {
                            case 1:
                                echo "Não Cancelado";
                                break;

                            case 2:
                                echo "Cancelado";
                                break;

                            default:
                                echo "Indefinido";
                                break;
                        }
                        ?></td>
                    <td width="20%">
                        <a href="/pedidos/visualiza/<?php echo $pedido->getIdPedido(); ?>" class="btn btn-purple btn-square"><i class="fa fa-search"></i> Visualizar</a>
                        <a href="/pedidos/fatura/<?php echo $pedido->getIdPedido(); ?>" class="btn btn-green btn-square"><i class="fa fa-dollar"></i> Fatura</a>
                        <?php
                        if ($pedido->getStatusPedido() == 1) {
                            ?><a href="#delete" data-toggle="tooltip" data-placement="top" title="Apagar" class="delete_open btn btn-red btn-square" onclick="cancelaPedido(<?php echo $pedido->getIdPedido(); ?>, '<?php echo $pedido->getIdPedido(); ?>');"><i class="fa fa-trash-o"></i> Cancelar</a><?php
                        } else {
                            ?><a href="/pedidos/ativa/<?php echo $pedido->getIdPedido(); ?>" class="btn btn-blue btn-square"><i class="fa fa-check"></i> Ativar</a><?php
                        }
                        ?>

                    </td>
                </tr>
                <?php } ?>
                </tbody>
                </table>
                </div>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Inline Form Example -->
</div>

<!-- Delete Notification Box -->
<div id="delete">
    <div class="logout-message">
        <br />
        <h3>
            <i class="fa fa-trash-o text-green"></i> Deseja Cancelar <b id="nome_pedido_apagar">--</b>?
        </h3>
        <p>Clique em "Sim" para cancelar este pedido.</p>
        <ul class="list-inline">
            <li>
                <a href="#" class="btn btn-green" id="url_pedido_apagar">
                    <strong>Sim</strong>
                </a>
            </li>
            <li>
                <button class="delete_close btn btn-green">Cancelar</button>
            </li>
        </ul>
    </div>
</div>
<!-- /#delete -->

<script>
    function cancelaPedido(id, nome)
    {
        $('#nome_pedido_apagar').html(nome);
        $('#url_pedido_apagar').attr('href', '/pedidos/cancela/' + id);
    }
</script>