<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Pedidos
                <small>Visualizar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Pedidos</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Horizontal Form Example -->
    <div class="col-lg-12">
        <a href="/pedidos" class="btn btn-default btn-square">Listar Pedidos</a>
        <br />
        <br />
        <div class="portlet portlet-green">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Visualizar Pedido</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#horizontalFormExample"><i class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="horizontalFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <form class="form-horizontal" role="form" method="POST" name="upload-form" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Código</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->pedido->getIdPedido(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Observações</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><pre class="tile blue"><?php echo $this->pedido->getObsPedido(); ?></pre></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Valor Total</label>
                            <div class="col-sm-10">
                                <label class="radio-inline">R$ <?php echo $this->pedido->getValorPedido(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Status</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php
                                    switch ($this->pedido->getStatusPedido()) {
                                        case 1:
                                            echo "Não Cancelado";
                                            break;

                                        case 2:
                                            echo "Cancelado";
                                            break;

                                        default:
                                            echo "Indefinido";
                                            break;
                                    }
                                    ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Cliente</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->cliente->getNomeCliente(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Atendente</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->atendente->getNomeFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Entregador</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->entregador->getNomeFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Caixa</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->caixa->getNomeFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Gerente</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo $this->gerente->getNomeFuncionario(); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Data</label>
                            <div class="col-sm-10">
                                <label class="radio-inline"><?php echo date('d/m/Y H:i:s', $this->pedido->getDtPedido()); ?></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Produtos</label>
                            <div class="col-sm-10">
                                <label class="radio-inline">
                                    <table id="example-table" class="table table-striped table-bordered table-hover table-green">
                                        <thead>
                                        <tr>
                                            <th>Código</th>
                                            <th>Nome</th>
                                            <th>Quantidade</th>
                                            <th>Valor Unitário</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $arrProdutos = json_decode($this->pedido->getProdutosPedido());

                                        foreach ($arrProdutos as $produto) {
                                            $objProduto = $this->produtoService->find($produto->idProduto);
                                            if ($objProduto == null) {
                                                continue;
                                            }
                                        ?>

                                        <tr>
                                            <td><?php echo $objProduto->getIdProduto(); ?></td>
                                            <td><?php echo $objProduto->getNomeProduto(); ?></td>
                                            <td><?php echo $produto->qtdProduto; ?></td>
                                            <td>R$ <?php echo $objProduto->getValorProduto(); ?></td>
                                        </tr>

                                        <?php } ?>

                                        </tbody>
                                    </table>
                                </label>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Horizontal Form Example -->
</div>